config/routes.rb
Rails.application.routes.draw do
  

  # get '/', to: 'pages#team'
  root to: 'pages#team' # same as previous

  # get 'pages/about'
  # same as previous line
  get 'pages/about', to: 'pages#about'
  
  get 'about', to: 'pages#about'

  get 'team', to: 'pages#team'

  get 'pages/contact'

  get 'restaurants/index'
  
  # get 'restaurants', to: 'restaurants#index'
  
  get 'restaurants', to: 'restaurants#index', as: :portuguese_restaurants

  # get 'restaurants/1', to: 'restaurants#show'
  # get 'restaurants/2', to: 'restaurants#show'
  #  this is stupid, just use variables
  #  
  get 'restaurants/:id', to: 'restaurants#show'

  post 'restaurants', to: 'restaurants#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  	
  end

  def team
  end
end

app/controllers/restaurants_controller.rb
require 'longest_word'

class RestaurantsController < ApplicationController
  # Let's fake a DB
  RESTAURANTS = [
                  { name: "Solar dos Presuntos", address: "Shoreditch, London", category: "indian" },
                  { name: "Tasca da Avenida", address: "City, London", category: "sushi" }
                ]

  def index
  	@restaurants = RESTAURANTS
  	if params[:food_type]
  		@restaurants =  @restaurants.select {|r| r[:category] == params[:food_type] } 
  	end

  	solution_methods
  end

  def create
  	render plain: "You tried to create a new restaurants with name #{params[:name]}" 
  end

  def show
  	@restaurant = RESTAURANTS[params[:id].to_i-1]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BenficaSporting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About US</h1>
<p>We are the best! We are! FU!</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/team.html.erb
<h1>Sporting sucks!</h1>

app/views/restaurants/index.html.erb
<!-- WRONG WAY OF USING RUBY CODE IN HTML FILE -->
<% restaurants = ['Frade Mares', 'Cantinho Lusitano', 'Charrua', 'Ramiro'] %>

<h1>Restaurants</h1>
<p>List updated at <%= Date.today %></p>


<!-- List restaurants -->
<ul>
<% restaurants.each do |r| %>
	<li><%= r %></li>
<% end %>
</ul>


<!-- Get form - params go on the url -->
<p>Get Form</p>
<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<!-- List restaurants using instance variables -->
<ul>
<% @restaurants.each do |r| %>
	<li><%= r[:name] %> - <%= r[:category] %></li>
<% end %>
</ul>


<p>Create new restaurant</p>
<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name">
  <input type="text" name="address">
  <input type="submit">
</form>

app/views/restaurants/show.html.erb
<h1>Restaurant <%= @restaurant[:name] %></h1>

<!-- HTML raw code -->
<a href="/restaurants">Go back to Restaurants</a>

<!-- ruby way of defining links, name, url -->
<%= link_to 'Go back to Restaurants', restaurants_path %>

<%= link_to 'Go back to Restaurants', portuguese_restaurants_path %>